version: "3"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: SAEroot
      MYSQL_DATABASE: dolibarrSAE
      MYSQL_USER: Admin1
      MYSQL_PASSWORD: minetest1234=+
    volumes:
      - mariadb_data:/var/lib/mysql
  
  phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        ports:
            - "8080:80"

  dolibarr:
        image: tuxgasy/dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: Admin1
            DOLI_DB_PASSWORD: minetest1234=+
            DOLI_DB_NAME: dolibarrSAE
            DOLI_URL_ROOT: 'http://localhost'
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
        ports:
            - "80:80"
        links:
            - mariadb
        volumes :
        - dolibarr_instlock:/var/www/documents
        - dolibarr_html:/var/www/html

  minetest:
    build:
      context : .
      dockerfile: minetest.Dockerfile
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/CET
      - "CLI_ARGS=--gameid minetest --port 30000" #optional
    volumes:
      - minetest_data:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped
    networks:
        - minetest_network       
  
  api:
    build:
      context: .
      dockerfile_inline: |
        FROM php:apache
        SHELL ["/bin/bash", "-c"]
        RUN ln -s ../mods-available/{expires,headers,rewrite}.load /etc/apache2/mods-enabled/
        RUN sed -e '/<Directory \/var\/www\/>/,/<\/Directory>/s/AllowOverride None/AllowOverride All/' -i /etc/apache2/apache2.conf
        COPY php.ini /usr/local/etc/php/
    networks:
        - minetest_network
    volumes:
        - api_data:/var/www/html
    ports:
        - 8081:80
  
    


volumes:
  mariadb_data:
  dolibarr_instlock:
  dolibarr_html:
  minetest_data:
  api_data:

networks:
    minetest_network:
